enum constants {
  GET_ARTICLES_REQUEST = "GET_ARTICLES_REQUEST",
  GET_ARTICLES_SUCCESS = "GET_ARTICLES_SUCCESS",
  GET_ARTICLES_FAILURE = "GET_ARTICLES_FAILURE",

  ADD_ARTICLE_REQUEST = "ADD_ARTICLE_REQUEST",
  ADD_ARTICLE_SUCCESS = "ADD_ARTICLE_SUCCESS",
  ADD_ARTICLE_FAILURE = "ADD_ARTICLE_FAILURE",

  DELETE_ARTICLE_REQUEST = "DELETE_ARTICLE_REQUEST",
  DELETE_ARTICLE_SUCCESS = "DELETE_ARTICLE_SUCCESS",
  DELETE_ARTICLE_FAILURE = "DELETE_ARTICLE_FAILURE",

  GET_ARTICLE_REQUEST = "GET_ARTICLE_REQUEST",
  GET_ARTICLE_SUCCESS = "GET_ARTICLE_SUCCESS",
  GET_ARTICLE_FAILURE = "GET_ARTICLE_FAILURE",

  UPDATE_ARTICLE_REQUEST = "UPDATE_ARTICLE_REQUEST",
  UPDATE_ARTICLE_SUCCESS = "UPDATE_ARTICLE_SUCCESS",
  UPDATE_ARTICLE_FAILURE = "UPDATE_ARTICLE_FAILURE",
}

export default constants;