enum constants {
    GET_COMPANY_NAME_REQUEST = "GET_COMPANY_NAME_REQUEST",
    GET_COMPANY_NAME_SUCCESS = "GET_COMPANY_NAME_SUCCESS",
    GET_COMPANY_NAME_FAILURE = "GET_COMPANY_NAME_FAILURE",

    GET_COMPANY_SHARE_CAPITAL_REQUEST = "GET_COMPANY_SHARE_CAPITAL_REQUEST",
    GET_COMPANY_SHARE_CAPITAL_SUCCESS = "GET_COMPANY_SHARE_CAPITAL_SUCCESS",
    GET_COMPANY_SHARE_CAPITAL_FAILURE = "GET_COMPANY_SHARE_CAPITAL_FAILURE",

    GET_VAT_NUMBER_REQUEST = "GET_VAT_NUMBER_REQUEST",
    GET_VAT_NUMBER_SUCCESS = "GET_VAT_NUMBER_SUCCESS",
    GET_VAT_NUMBER_FAILURE = "GET_VAT_NUMBER_FAILURE",

    GET_COMPANY_ADDRESS_REQUEST = "GET_COMPANY_ADDRESS_REQUEST",
    GET_COMPANY_ADDRESS_SUCCESS = "GET_COMPANY_ADDRESS_SUCCESS",
    GET_COMPANY_ADDRESS_FAILURE = "GET_COMPANY_ADDRESS_FAILURE",

    UPDATE_VAT_NUMBER_REQUEST = "UPDATE_VAT_NUMBER_REQUEST",
    UPDATE_VAT_NUMBER_SUCCESS = "UPDATE_VAT_NUMBER_SUCCESS",
    UPDATE_VAT_NUMBER_FAILURE = "UPDATE_VAT_NUMBER_FAILURE",
}

export default constants;