enum constants {
  GET_CUSTOMERS_REQUEST = "GET_CUSTOMERS_REQUEST",
  GET_CUSTOMERS_SUCCESS = "GET_CUSTOMERS_SUCCESS",
  GET_CUSTOMERS_FAILURE = "GET_CUSTOMERS_FAILURE",
  
  ADD_CUSTOMER_REQUEST = "ADD_CUSTOMER_REQUEST",
  ADD_CUSTOMER_SUCCESS = "ADD_CUSTOMER_SUCCESS",
  ADD_CUSTOMER_FAILURE = "ADD_CUSTOMER_FAILURE",

  DELETE_CUSTOMER_REQUEST = "DELETE_CUSTOMER_REQUEST",
  DELETE_CUSTOMER_SUCCESS = "DELETE_CUSTOMER_SUCCESS",
  DELETE_CUSTOMER_FAILURE = "DELETE_CUSTOMER_FAILURE",

  UPDATE_CUSTOMER_REQUEST = "UPDATE_CUSTOMER_REQUEST",
  UPDATE_CUSTOMER_SUCCESS = "UPDATE_CUSTOMER_SUCCESS",
  UPDATE_CUSTOMER_FAILURE = "UPDATE_CUSTOMER_FAILURE",

  GET_CUSTOMER_REQUEST = "GET_CUSTOMER_REQUEST",
  GET_CUSTOMER_SUCCESS = "GET_CUSTOMER_SUCCESS",
  GET_CUSTOMER_FAILURE = "GET_CUSTOMER_FAILURE",
}

export default constants;