enum constants {
  GET_PAYMENT_TERMS_REQUEST = "GET_PAYMENT_TERMS_REQUEST",
  GET_PAYMENT_TERMS_SUCCESS = "GET_PAYMENT_TERMS_SUCCESS",
  GET_PAYMENT_TERMS_FAILURE = "GET_PAYMENT_TERMS_FAILURE",

  ADD_PAYMENT_TERM_REQUEST = "ADD_PAYMENT_TERM_REQUEST",
  ADD_PAYMENT_TERM_SUCCESS = "ADD_PAYMENT_TERM_SUCCESS",
  ADD_PAYMENT_TERM_FAILURE = "ADD_PAYMENT_TERM_FAILURE",

  UPDATE_PAYMENT_TERM_REQUEST = "UPDATE_PAYMENT_TERM_REQUEST",
  UPDATE_PAYMENT_TERM_SUCCESS = "UPDATE_PAYMENT_TERM_SUCCESS",
  UPDATE_PAYMENT_TERM_FAILURE = "UPDATE_PAYMENT_TERM_FAILURE",

  GET_PAYMENT_TERM_REQUEST = "GET_PAYMENT_TERM_REQUEST",
  GET_PAYMENT_TERM_SUCCESS = "GET_PAYMENT_TERM_SUCCESS",
  GET_PAYMENT_TERM_FAILURE = "GET_PAYMENT_TERM_FAILURE",

  GET_INVOICE_TYPES_REQUEST = "GET_INVOICE_TYPES_REQUEST",
  GET_INVOICE_TYPES_SUCCESS = "GET_INVOICE_TYPES_SUCCESS",
  GET_INVOICE_TYPES_FAILURE = "GET_INVOICE_TYPES_FAILURE",

  GET_INVOICE_TYPE_REQUEST = "GET_INVOICE_TYPE_REQUEST",
  GET_INVOICE_TYPE_SUCCESS = "GET_INVOICE_TYPE_SUCCESS",
  GET_INVOICE_TYPE_FAILURE = "GET_INVOICE_TYPE_FAILURE",

  ADD_INVOICE_TYPE_REQUEST = "ADD_INVOICE_TYPE_REQUEST",
  ADD_INVOICE_TYPE_SUCCESS = "ADD_INVOICE_TYPE_SUCCESS",
  ADD_INVOICE_TYPE_FAILURE = "ADD_INVOICE_TYPE_FAILURE",

  UPDATE_INVOICE_TYPE_REQUEST = "UPDATE_INVOICE_TYPE_REQUEST",
  UPDATE_INVOICE_TYPE_SUCCESS = "UPDATE_INVOICE_TYPE_SUCCESS",
  UPDATE_INVOICE_TYPE_FAILURE = "UPDATE_INVOICE_TYPE_FAILURE",

  GET_PAYMENT_TERMS_ACTIVE_REQUEST = "GET_PAYMENT_TERMS_ACTIVE_REQUEST",
  GET_PAYMENT_TERMS_ACTIVE_SUCCESS = "GET_PAYMENT_TERMS_ACTIVE_SUCCESS",
  GET_PAYMENT_TERMS_ACTIVE_FAILURE = "GET_PAYMENT_TERMS_ACTIVE_FAILURE",

  GET_TAXES_REQUEST = "GET_TAX_RATES_REQUEST",
  GET_TAXES_SUCCESS = "GET_TAX_RATES_SUCCESS",
  GET_TAXES_FAILURE = "GET_TAX_RATES_FAILURE",

  GET_UNITS_REQUEST = "GET_UNITS_REQUEST",
  GET_UNITS_SUCCESS = "GET_UNITS_SUCCESS",
  GET_UNITS_FAILURE = "GET_UNITS_FAILURE",

  GET_TAX_EXEMPTION_REASONS_REQUEST = "GET_TAX_EXEMPTION_REASONS_REQUEST",
  GET_TAX_EXEMPTION_REASONS_SUCCESS = "GET_TAX_EXEMPTION_REASONS_SUCCESS",
  GET_TAX_EXEMPTION_REASONS_FAILURE = "GET_TAX_EXEMPTION_REASONS_FAILURE",

  GET_SAFT_PRODUCT_TYPE_REQUEST = "GET_SAFT_PRODUCT_TYPE_REQUEST",
  GET_SAFT_PRODUCT_TYPE_SUCCESS = "GET_SAFT_PRODUCT_TYPE_SUCCESS",
  GET_SAFT_PRODUCT_TYPE_FAILURE = "GET_SAFT_PRODUCT_TYPE_FAILURE",

  GET_DOCUMENT_TYPES_REQUEST = "GET_DOCUMENT_TYPES_REQUEST",
  GET_DOCUMENT_TYPES_SUCCESS = "GET_DOCUMENT_TYPES_SUCCESS",
  GET_DOCUMENT_TYPES_FAILURE = "GET_DOCUMENT_TYPES_FAILURE",

  GET_DOCUMENT_TYPE_REQUEST = "GET_DOCUMENT_TYPE_REQUEST",
  GET_DOCUMENT_TYPE_SUCCESS = "GET_DOCUMENT_TYPE_SUCCESS",
  GET_DOCUMENT_TYPE_FAILURE = "GET_DOCUMENT_TYPE_FAILURE",

  ADD_DOCUMENT_TYPE_REQUEST = "ADD_DOCUMENT_TYPE_REQUEST",
  ADD_DOCUMENT_TYPE_SUCCESS = "ADD_DOCUMENT_TYPE_SUCCESS",
  ADD_DOCUMENT_TYPE_FAILURE = "ADD_DOCUMENT_TYPE_FAILURE",

  UPDATE_DOCUMENT_TYPE_REQUEST = "UPDATE_DOCUMENT_TYPE_REQUEST",
  UPDATE_DOCUMENT_TYPE_SUCCESS = "UPDATE_DOCUMENT_TYPE_SUCCESS",
  UPDATE_DOCUMENT_TYPE_FAILURE = "UPDATE_DOCUMENT_TYPE_FAILURE",
}

export default constants;