enum constants {
  GET_INVOICES_REQUEST = "GET_INVOICES_REQUEST",
  GET_INVOICES_SUCCESS = "GET_INVOICES_SUCCESS",
  GET_INVOICES_FAILURE = "GET_INVOICES_FAILURE",

  ADD_INVOICE_REQUEST = "ADD_INVOICE_REQUEST",
  ADD_INVOICE_SUCCESS = "ADD_INVOICE_SUCCESS",
  ADD_INVOICE_FAILURE = "ADD_INVOICE_FAILURE",

  UPDATE_INVOICE_REQUEST = "UPDATE_INVOICE_REQUEST",
  UPDATE_INVOICE_SUCCESS = "UPDATE_INVOICE_SUCCESS",
  UPDATE_INVOICE_FAILURE = "UPDATE_INVOICE_FAILURE",

  DELETE_INVOICE_REQUEST = "DELETE_INVOICE_REQUEST",
  DELETE_INVOICE_SUCCESS = "DELETE_INVOICE_SUCCESS",
  DELETE_INVOICE_FAILURE = "DELETE_INVOICE_FAILURE",

  GET_INVOICE_REQUEST = "GET_INVOICE_REQUEST",
  GET_INVOICE_SUCCESS = "GET_INVOICE_SUCCESS",
  GET_INVOICE_FAILURE = "GET_INVOICE_FAILURE",
}

export default constants;