enum constants {
    LOGIN_REQUEST = "LOGIN_REQUEST",
    LOGIN_SUCCESS = "LOGIN_SUCCESS",
    LOGIN_FAILURE = "LOGIN_FAILURE",

    RECOVER_REQUEST = "RECOVER_REQUEST",
    RECOVER_SUCCESS = "RECOVER_SUCCESS",
    RECOVER_FAILURE = "RECOVER_FAILURE",

    GET_USERS_REQUEST = "GET_USERS_REQUEST",
    GET_USERS_SUCCESS = "GET_USERS_SUCCESS",
    GET_USERS_FAILURE = "GET_USERS_FAILURE",

    GET_USER_REQUEST = "GET_USER_REQUEST",
    GET_USER_SUCCESS = "GET_USER_SUCCESS",
    GET_USER_FAILURE = "GET_USER_FAILURE",

    ADD_USER_REQUEST = "ADD_USER_REQUEST",
    ADD_USER_SUCCESS = "ADD_USER_SUCCESS",
    ADD_USER_FAILURE = "ADD_USER_FAILURE",

    UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST",
    UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS",
    UPDATE_USER_FAILURE = "UPDATE_USER_FAILURE",
}

export default constants;